server {
    listen 80;
    server_name localhost 100.116.54.101;

#front
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

#back
    location /api/ {
        resolver 127.0.0.11 valid=30s;
        set $backend_service backend-spring;
        proxy_pass http://$backend_service:8080; 
        proxy_set_header Host $host;
        proxy_set_header Real-IP $remote_addr;
    }
}